### ISSUE TITLE
Doesn't work with Ducky Shine 7

### ISSUE THREAD

**Issue by ocp15k** [Vidalee/DuckyVisual#2]
I ran the exe while my Ducky Shine 7 plugged it and it comes up with 'Make sure your keyboard is connected!"

**Comment by ocp15k** [comment]
There is a group of us here at Aurora: https://github.com/antonpup/Aurora

We are adding support for more and more RGB keyboards/mice/RGB peripherals for special lighting effects Synchronised with most lighting systems like: Razer, Steelseries, Corsair, Logitech and many people want to get Ducky working too. 

According to one of Aurora's admins, your DuckyVisual contribution should work with Aurora if it works with Ducky Shine 7.

Welcome to hit us up on the Aurora Discord: https://discord.gg/QaVkfC.
My username is OCP on discord. You could contact me or thatsickman. 

Looking forward to hear from you and get this working together!

**Comment by Vidalee** [comment]
Closed, as I joined their discord.
